language: haskell
before_install:
  - cabal install alex
install:
  - cabal install --only-dependencies --enable-tests --force-reinstalls
script:
  - cabal configure --enable-tests && cabal build && ./dist/build/spec/spec
