language: haskell
before_install:
- openssl aes-256-cbc -K $encrypted_70aba0a032ac_key -iv $encrypted_70aba0a032ac_iv
  -in escualo_rsa.enc -out escualo_rsa -d
- cabal install alex
install:
- cabal install --only-dependencies --enable-tests --force-reinstalls
script:
- cabal configure --enable-tests && cabal build && ./dist/build/spec/spec
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo/master/travis_deploy
  && chmod u+x travis_deploy && ./travis_deploy mulang runners.mumuki.io
deploy:
  provider: releases
  api_key:
    secure: MQzUc43kSEXHf+CV1oqxky2QFd9MGnx1mIgtfR6xc9pCOSNHX9XXob9k7ki4Z8xJlIhvY3f+mnqADsniRg5OvQSbqxYbCF/lrLCXylgkOZXrN5k7O3thi4tZn5MwCJ66uFDGbUHvzH1T9hEoJ2L6D+YxKKUPOmJIBTdttbIBFm3zrIU6IlMzPSTUUreKN89i8ELK/jmpN2pokVcFz5ijBuety8iEEWtqqDM310iHx0/xwW/ULA/QjiDcMbMH+v5W4A+EZfBa7CoAHOsjzKxjSrSn3ZTYck9iVYX9X5f4+NuN1xcSCyK7++KnVEED4ZrsTvNUFijbKDhg0a4q/yqIR4fKyxiL+ANhH6AYn4/RZYJw3L2lJ02Srt+9h2/uSYDCTtExADo5dyEbrt+VRYfCiLxZaMlCIaRaVxYCMV231Td0+wYjB6MPNmy+hGCdxkHpNjzkFnOnWDfVfcsMP2+eWn8nec/4WrT8dKRtLG3+ivY5H0a1K0F1Batoo0kXaz6JTqb68nQS6DKm30KcvbST9hFA4Bhk9ceuIxPDH3iaS708EneI8lzwThrxBGsiyGX8FynIV9u+y13USfltcSQ7g64turwK1k5YQnAtUV3VQllGfsjmTruBu+F+B57w4zrHglAGPQgKfeft1VCXp3cOdtJBvRTUfrsbeyOgBvjS9mo=
  file: dist/build/mulang/mulang
  on:
    repo: mumuki/mulang
