language: haskell
before_install:
- openssl aes-256-cbc -K $encrypted_70aba0a032ac_key -iv $encrypted_70aba0a032ac_iv
  -in escualo_rsa.enc -out escualo_rsa -d
- cabal install alex
install:
- cabal install --only-dependencies --enable-tests --force-reinstalls
script:
- cabal configure --enable-tests && cabal build && ./dist/build/spec/spec
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo/master/travis_deploy
  && chmod u+x travis_deploy && ./travis_deploy mulang runners.mumuki.io
deploy:
  provider: releases
  api_key:
    secure: MQzUc43kSEXHf+CV1oqxky2QFd9MGnx1mIgtfR6xc9pCOSNHX9XXob9k7ki4Z8xJlIhvY3f+mnqADsniRg5OvQSbqxYbCF/lrLCXylgkOZXrN5k7O3thi4tZn5MwCJ66uFDGbUHvzH1T9hEoJ2L6D+YxKKUPOmJIBTdttbIBFm3zrIU6IlM
  file: dist/build/mulang/mulang
  on:
    repo: mumuki/mulang

