resolver: lts-12.13
packages:
- '.'
extra-deps:
# Using newest aeson, with no contents in tagged
# unions with nullary constructors
- github: mumuki/language-javascript
  commit: 3640442ea562cc125f219b5c60fbc1b77882fd62
- github: julian-berbel/language-python
  commit: cbdf9b33cc3c30e66c8455165ed1c7d70a300a3e
flags: {}
extra-package-dbs: []
