resolver: lts-7.24
packages:
- '.'
extra-deps:
# Using newest aeson, with no contents in tagged
# unions with nullary constructors
- aeson-1.2.1.0
- github: erikd/language-javascript
  commit: 5257216640a1d769abd8650b7b069a2d28354ffa
- github: julian-berbel/language-python
  commit: cbdf9b33cc3c30e66c8455165ed1c7d70a300a3e
flags: {}
extra-package-dbs: []
