resolver: lts-7.24
packages:
- '.'
extra-deps:
# Using newest aeson, with no contents in tagged
# unions with nullary constructors
- aeson-1.2.1.0
# Using older javascript dep, compatible with
# current AST
- language-javascript-0.5.14.7
flags: {}
extra-package-dbs: []
