name: Test and deploy

on:
- push
- workflow_dispatch

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.6.3
    - name: Generate template files
      run: ./generators/run
    - name: Haskell - prep, build, test, and install binaries
      run: |
        docker run -v $PWD:/root/mulang -v $HOME/.local/bin:/root/.local/bin haskell:8.0.1 bash -c '
          set -e

          stack upgrade --binary-version 1.9.3
          export PATH=/root/.local/bin:$PATH

          cd /root/mulang

          stack --no-terminal --skip-ghc-check --allow-different-user test
          stack --no-terminal --skip-ghc-check --allow-different-user install
        '
    - name: Wrap gem
      run: ./bin/setup
      working-directory: gem
    - name: Run ruby tests
      run: bundle exec rake
      working-directory: gem
